apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
spec:
  replicas: 2
  strategy: {}
  selector:
    matchLabels:
      run: flask-application
  template:
    metadata:
      labels:
        run: flask-application
    spec:
      containers:
      - name: spellcheckwebapp
        image: kurlee/spellcheckwebapp
        ports:
        - containerPort: 8080
      restartPolicy: Always
