apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: flask-application
  name: flask-application
spec:
  replicas: 5
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: flask-application
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: flask-application
    spec:
      containers:
      - image: kurlee/spellcheckwebapp
        name: spellcheckwebapp
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
