apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
spec:
  replicas: 5
  selector:
    matchLabels:
      run: flask-application
  template:
    metadata:
      labels:
        run: flask-application
    spec:
      containers:
      - name: spellcheckwebapp
        image: kurlee/spellcheckwebapp
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.5"
            memory: "100Mi"
        args:
          - -cpus
          - "2"
      restartPolicy: Always
