apiVersion: v1
kind: Service
metadata:
  name: flask-application
  namespace: hellonyu
  labels:
    name: flask-application
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: flask-application-one
    io.kompose.service: flask-application-two
