# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.4.2-stable2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-11-19T01:50:24Z"
  labels:
    app: boringraman
  name: boringraman
spec:
  containers:
  - command:
    - gunicorn
    - SpellCheckApp:this_app
    - --bind
    - 0.0.0.0:8080
    - --workers
    - "5"
    env:
    - name: PATH
      value: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
    - name: container
      value: podman
    - name: LANG
      value: C.UTF-8
    - name: GPG_KEY
      value: E3FF2839C048B25C084DEBE9B26995E310250568
    - name: PYTHON_VERSION
      value: 3.8.0
    - name: PYTHON_PIP_VERSION
      value: 19.3.1
    - name: PYTHON_GET_PIP_URL
      value: https://github.com/pypa/get-pip/raw/ffe826207a010164265d9cc807978e3604d18ca0/get-pip.py
    - name: PYTHON_GET_PIP_SHA256
      value: b86f36cc4345ae87bfd4f10ef6b2dbfa7a872fbff70608a1e43944d283fd0eee
    image: docker.io/kurlee/spellcheckwebapp:latest
    name: boringraman
    ports:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /SpellCheckerWebapp/
status: {}

